// src/mockData.ts

import { Book } from "../Models/Book";


export const mockBooks: Book[] = [
  {
    Id: "1",
    Title: "Sample Book 1",
    Author: "John Doe",
    Genre: "Science Fiction",
    Description: "A sci-fi book",
    ISBN: "123-456-789",
    CoverImageUrl: "https://m.media-amazon.com/images/I/71o4HTng33L._AC_UF894,1000_QL80_.jpg",
    PublicationDate: "2023-01-01T00:00:00Z",
    PageCount: 320,
    Language: "English",
    Format: "eBook",
    Keywords: "Sci-Fi, Adventure",
    IsAvailable: true,
    Publisher: { UserName: "BestPublisher" },
    Reviews: [],
  },
  {
    Id: "2",
    Title: "Sample Book 2",
    Author: "Jane Smith",
    Genre: "Fantasy",
    Description: "A fantasy book",
    ISBN: "987-654-321",
    CoverImageUrl: "https://m.media-amazon.com/images/I/71o4HTng33L._AC_UF894,1000_QL80_.jpg",
    PublicationDate: "2022-05-15T00:00:00Z",
    PageCount: 450,
    Language: "English",
    Format: "Hardcover",
    Keywords: "Fantasy, Magic",
    IsAvailable: false,
    Publisher: { UserName: "AnotherPublisher" },
    Reviews: [],
  },
  {
    Id: "3",
    Title: "Sample Book 2",
    Author: "Jane Smith",
    Genre: "Fantasy",
    Description: "A fantasy book",
    ISBN: "987-654-321",
    CoverImageUrl: "https://m.media-amazon.com/images/I/71o4HTng33L._AC_UF894,1000_QL80_.jpg",
    PublicationDate: "2022-05-15T00:00:00Z",
    PageCount: 450,
    Language: "English",
    Format: "Hardcover",
    Keywords: "Fantasy, Magic",
    IsAvailable: false,
    Publisher: { UserName: "AnotherPublisher" },
    Reviews: [],
  },
  {
    Id: "4",
    Title: "Sample Book 2",
    Author: "Jane Smith",
    Genre: "Fantasy",
    Description: "A fantasy book",
    ISBN: "987-654-321",
    CoverImageUrl: "https://m.media-amazon.com/images/I/71o4HTng33L._AC_UF894,1000_QL80_.jpg",
    PublicationDate: "2022-05-15T00:00:00Z",
    PageCount: 450,
    Language: "English",
    Format: "Hardcover",
    Keywords: "Fantasy, Magic",
    IsAvailable: false,
    Publisher: { UserName: "AnotherPublisher" },
    Reviews: [],
  },
  {
    Id: "5",
    Title: "Sample Book 2",
    Author: "Jane Smith",
    Genre: "Fantasy",
    Description: "A fantasy book",
    ISBN: "987-654-321",
    CoverImageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStMHp6TK_pzJjp3nclbzuOg6FXY0t73CA8qw&s",
    PublicationDate: "2022-05-15T00:00:00Z",
    PageCount: 450,
    Language: "English",
    Format: "Hardcover",
    Keywords: "Fantasy, Magic",
    IsAvailable: false,
    Publisher: { UserName: "AnotherPublisher" },
    Reviews: [],
  },
  {
    Id: "6",
    Title: "Sample Book 2",
    Author: "Jane Smith",
    Genre: "Fantasy",
    Description: "A fantasy book",
    ISBN: "987-654-321",
    CoverImageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6H69MBftbfTYP-CYec9wSM3KRJf-2gkXrVA&s",
    PublicationDate: "2022-05-15T00:00:00Z",
    PageCount: 450,
    Language: "English",
    Format: "Hardcover",
    Keywords: "Fantasy, Magic",
    IsAvailable: false,
    Publisher: { UserName: "AnotherPublisher" },
    Reviews: [],
  },
];
